//
//  TrackMe.swift
//  TrackMe
//
//  Created by KaiZen Enterprises on 14/5/17.
//  Copyright (c) 2017 KaiZen Enterprises. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//


import UIKit

public class TrackMe: NSObject {
	
	//// Drawing Methods
	
	public class func drawCompass(frame: CGRect = CGRect(x: 0, y: 0, width: 320, height: 320)) {
		
		
		//// Subframes
		let group: CGRect = CGRect(x: frame.minX + 2, y: frame.minY, width: floor((frame.width - 2) * 0.99371 + 0.5), height: floor((frame.height) * 0.98750 + 0.5))
		
		
		//// Group
		//// Oval Drawing
		let ovalPath = UIBezierPath(ovalIn: CGRect(x: group.minX + floor(group.width * 0.00000 + 0.5), y: group.minY + floor(group.height * 0.00000 + 0.5), width: floor(group.width * 1.00000 + 0.5) - floor(group.width * 0.00000 + 0.5), height: floor(group.height * 1.00000 + 0.5) - floor(group.height * 0.00000 + 0.5)))
		UIColor.white.setStroke()
		ovalPath.lineWidth = 1
		ovalPath.stroke()
		
		
		//// Bezier Drawing
		let bezierPath = UIBezierPath()
		bezierPath.move(to: CGPoint(x: group.minX + 0.50000 * group.width, y: group.minY + 0.00158 * group.height))
		bezierPath.addLine(to: CGPoint(x: group.minX + 0.46835 * group.width, y: group.minY + 0.06487 * group.height))
		bezierPath.addLine(to: CGPoint(x: group.minX + 0.53165 * group.width, y: group.minY + 0.06487 * group.height))
		bezierPath.addLine(to: CGPoint(x: group.minX + 0.50000 * group.width, y: group.minY + 0.00158 * group.height))
		bezierPath.close()
		UIColor.white.setStroke()
		bezierPath.lineWidth = 1
		bezierPath.stroke()
	}
	
}
